#! /usr/bin/env python3

import argparse
import requests
import time


class PushOver:
    def __init__(self):
        self._token = "ayjy9skodczzm5itx3mi93tbm4jysp"
        self._user = "ug8wpig4ajf1vaoxkbw5uwuoed7fbm"

    def send(self, title, message, priority=0):
        payload = {
            "token": self._token,
            "user": self._user,
            "priority": priority,
            "title": title,
            "message": message,
            "timestamp": int(time.time()),
        }

        req = requests.post("https://api.pushover.net/1/messages.json", params=payload)
        req.raise_for_status()


def main():
    parser = argparse.ArgumentParser(description="Push over wrapper")
    parser.add_argument("-p", "--priority", choices=[-2, -1, 0, 1], default=0)
    parser.add_argument("-t", "--title", type=str, default=None)
    parser.add_argument("message", metavar="message", type=str, nargs="+")
    args = parser.parse_args()

    push_over = PushOver()
    push_over.send(args.title, " ".join(args.message), args.priority)


if __name__ == "__main__":
    main()
